
unstable_features = true

tab_spaces = 4
blank_lines_lower_bound = 0
blank_lines_upper_bound = 7

imports_granularity = "One"

wrap_comments = true
comment_width = 90

float_literal_trailing_zero = "Always"
